### ISSUE TITLE
Bank of Scotland Branch Closures

### ISSUE THREAD

**Issue by chrisfleming** [osm-scotland/scotland-issues#12]
Bank of Scotland:

- [x] Paisly South 5th February 2019
- [x] Burnside 18 Feb 2020
- [x] Dundee 19 Feb 2020
- [x] Glasgow St George Cross - 20 Feb
- [x] Stonehouse 26 February 2019
- [x] Livingston 1 March 2021
- [x] Tullos, Aberdeen 9 March 2021
- [x] Loanhead - 15 March 2021
- [x] Galston  - 16 March 2021
- [x] Edinburgh Dalry Road - 16 March 2021
- [x] Grantown-on-Spey - 22 March 2021
- [x] Kinross - 22 March 2021
- [ ] Balfron 23 March 2021
- [ ] Killin 24 March 2021
- [ ] Auchterader - 25 March 2021
- [ ] Huntly  - 29 March 2021
- [ ] Turriff -30 March
- [ ] Edinburgh Liberton - 31 March 2021
- [ ] Edinburgh Tollcross  26 April 2021
- [ ] Edinburgh Greenside  26 April 2021

Already Closed:

- [x] Keith 20 May
- [x] Kirriemuir  20 May
- [x] Lossiemouth 3 June

**Comment by boothym** [comment]
Think these have all been removed?

**Comment by chrisfleming** [comment]
Great I slightly ran out of steam on these. But will close this if we're all up to date.
