### ISSUE TITLE
Scottish Water top up taps

### ISSUE THREAD

**Issue by boothym** [osm-scotland/scotland-issues#20]
Scottish Water have been installing public water taps: https://www.yourwateryourlife.co.uk/find-your-nearest-top-up-tap/

Their website source code actually contains the co-ordinates of each tap which is displayed on their map above, and it is accurate for the ones already mapped in OSM here: https://overpass-turbo.eu/s/1ciW - so definitely something we could import.

I asked them about permission to use the lat/lon in OSM via the OSMScotland Twitter, then emailed (no reply), and then two weeks later chased them up again on Twitter. However none of their replies actually relate to the question I asked! :neutral_face:

So the issue is - do we definitely need permission (I assume so) and is there a form of words Scottish Water will understand to allow us to use the co-ordinates? Or do we just wait until people eventually get round to surveying them?

**Comment by chrisfleming** [comment]
I've been following the tweets! Don't think that anyone is really actually reading our questions.

Apart from trying to find a better contact at Scottish Water, I think our best bet is to drop notes and hopefuly someome can confirm the locations.

**Comment by boothym** [comment]
Thanks. Think I'll try asking them again and then begin adding notes, or adding taps where news of the location has been posted about on social media (so it's not just adding straight from their website) - e.g. https://twitter.com/SWsoutheast/status/1432640936992034820/photo/1

**Comment by boothym** [comment]
Got permission via Twitter DM, conflated and imported the locations into OSM.
